=== Spejderneslejr/display-templates/src/slideshow/slideshow-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/os2display/display-templates/blob/develop/src/slideshow/slideshow-schema.json",
  "title": "slideshow schema",
  "description": "Content schema for slideshow",
  "type": "object",
  "properties": {
    "images": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "animations": {
      "type": "string"
    },
    "logo": {
      "type": "string"
    },
    "transitions": {
      "type": "string"
    },
    "imageDuration": {
      "type": "number"
    }
  }
}

=== Spejderneslejr/display-templates/src/slideshow/slideshow-content-example.json
{
  "images": [
    "/v1/media/00000000000000000000000001",
    "/v1/media/00000000000000000000000002",
    "/v1/media/00000000000000000000000003",
    "/v1/media/00000000000000000000000004"
  ],
  "logo": "/v1/media/00000000000000000000000001",
  "transitions": "fade",
  "animations": "random",
  "imageDuration": 5000
}
