=== Spejderneslejr/display-templates/src/table/table-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "backgroundImage": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "title": {
      "type": "string"
    },
    "text": {
      "type": "string"
    },
    "styling": {
      "type": "object",
      "properties": {
        "fontPlacement": {
          "type": "string"
        },
        "fontSize": {
          "type": "string"
        }
      },
      "required": [
        "fontPlacement",
        "fontSize"
      ]
    },
    "table": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "columns": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "title": {
                      "type": "string"
                    },
                    "field": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "title",
                    "field"
                  ]
                },
                {
                  "type": "object",
                  "properties": {
                    "title": {
                      "type": "string"
                    },
                    "field": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "title",
                    "field"
                  ]
                }
              ]
            }
          },
          "required": [
            "type",
            "columns"
          ]
        },
        {
          "type": "object",
          "properties": {
            "column1": {
              "type": "string"
            },
            "column2": {
              "type": "string"
            }
          },
          "required": [
            "column1",
            "column2"
          ]
        }
      ]
    }
  },
  "required": [
    "backgroundImage",
    "title",
    "text",
    "styling",
    "table"
  ]
}

=== Spejderneslejr/display-templates/src/table/table-content-example.json
{
  "backgroundImage": [
    "/v1/media/00000000000000000000000001"
  ],
  "title": "Overskrift",
  "text": "Da dadadad dad aa da dadadad dad aa da dadadad dad aa da dadadad dad aa da dadadad dad aa da dadadad dad aadadadad dad aa da dadadad dad aa da dadadad dad aa da dadadad dad aa da dadadad dad aa da dadadad dad aa",
  "styling": {
    "fontPlacement": "bottom",
    "fontSize": "s"
  },
  "table": [
    {
      "type": "header",
      "columns": [
        {
          "title": "Column 1",
          "field": "column1"
        },
        {
          "title": "Column 2",
          "field": "column2"
        }
      ]
    },
    {
      "column1": "Data 1",
      "column2": "Data 2"
    },
    {
      "column1": "Data 3",
      "column2": "Data 4"
    }
  ]
}
