=== Spejderneslejr/display-templates/src/config-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://display-templates.local.itkdev.dk/config-schema.json",
  "title": "Config file schema",
  "description": "Schema for defining config files for templates",
  "type": "object",
  "properties": {
    "icon": {
      "description": "An icon for the template",
      "type": "string"
    },
    "description": {
      "description": "A description of the template",
      "type": "string"
    },
    "resources": {
      "type": "object",
      "properties": {
        "schema": {
          "description": "Path to the json schema for the content",
          "type": "string"
        },
        "component": {
          "description": "Path to the react remote component that renders the content",
          "type": "string"
        },
        "admin": {
          "description": "Path to the json array describing the content form in the administration interface",
          "type": "string"
        }
      }
    },
    "title": {
      "description": "The title of the template",
      "type": "string"
    }
  }
}

=== Spejderneslejr/display-templates/src/slideshow/slideshow.json
{
  "title": "Slideshow",
  "icon": "",
  "description": "Skabelon til slideshow af billeder med forskellige effekter",
  "resources": {
    "component": "https://raw.githubusercontent.com/os2display/display-templates/develop/build/slideshow.js",
    "admin": "https://raw.githubusercontent.com/os2display/display-templates/develop/src/slideshow/slideshow-admin.json",
    "schema": "https://raw.githubusercontent.com/os2display/display-templates/develop/src/slideshow/slideshow-schema.json",
    "assets": [],
    "options": {},
    "content": {}
  }
}

=== Spejderneslejr/display-templates/src/image-text/image-text.json
{
  "title": "Billede og tekst",
  "icon": "",
  "description": "Mulighed for at s√¶tte billede og tekst, med forskellige visninger.",
  "resources": {
    "component": "https://raw.githubusercontent.com/os2display/display-templates/develop/build/image-text.js",
    "admin": "https://raw.githubusercontent.com/os2display/display-templates/develop/src/image-text/admin.json",
    "schema": "https://raw.githubusercontent.com/os2display/display-templates/develop/src/image-text/schema.json"
  }
}

=== Spejderneslejr/display-templates/src/book-review/book-review.json
{
  "title": "Anmeldelse",
  "icon": "",
  "description": "Skabelon til anmeldelser.",
  "resources": {
    "component": "https://raw.githubusercontent.com/os2display/display-templates/develop/build/book-review.js",
    "admin": "https://raw.githubusercontent.com/os2display/display-templates/develop/src/book-reviewt/admin.json",
    "schema": "https://raw.githubusercontent.com/os2display/display-templates/develop/src/book-review/schema.json"
  }
}
